features:
  - aliases
  - exec

aliases:
  - |
    /plugin (.*) -> /label plugin/$1
  - |
    /wai -> /label works as intended
  - |
    /release (.*) -> /exec /opt/bin/release-dnserver $1
  - |
    /docker (.*) -> /exec /opt/bin/docker-dnserver $1
